services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "8999:8999"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8999/health"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3999:3999"
    network_mode: "host"
    depends_on:
      backend:
        condition: service_healthy  # Wait until backend is "healthy"