services:
  server:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile.production
      network: "host"
    network_mode: "host"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8002/health"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes:
      - ./backend/.env.secrets:/app/backend/.env.secrets:ro
  client:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile.production
      network: "host"
    network_mode: "host"
    depends_on:
      server:
        condition: service_healthy  # Wait until backend is "healthy"
  server-staging:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile.staging
      network: "host"
    network_mode: "host"
    volumes:
      - ./backend/.env.secrets:/app/backend/.env.secrets:ro
  client-staging:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile.staging
      network: "host"
    network_mode: "host"